### ISSUE TITLE
Failed to minify the code from this file: ./node_modules/react-s3/lib/ReactS3.js:6

### ISSUE THREAD

**Issue by matveychuk** [Fausto95/aws-s3#11]
I use CRA and when trying to create a build file receive the next error: 
Failed to minify the code from this file:
 ./node_modules/react-s3/lib/ReactS3.js:6
Read more here: http://bit.ly/2tRViJ9
According to the given link it's problem that the library is published not production ready.  How it can be fixed?
Thank you in advance for answer

**Comment by Fausto95** [comment]
Can you install the latest version `v1.5.0` ?

**Comment by BrackCarmony** [comment]
It looks like 1.3.1 is the latest that has been pushed to npm.

**Comment by Fausto95** [comment]
@BrackCarmony use `npm install --save aws-s3`instead

**Comment by Evert-jvv** [comment]
+1 same issue, using aws-s3 v1.5

**Comment by guizero** [comment]
Same problem here. Does anyone know how to fix or bypass this?

**Comment by gatesyp** [comment]
@guizero You can clone his clone his repo, and copy over his source code into your own project. 

I cloned his repo, copied contents of the ```src``` directory to my own ```components/aws-s3``` folder, and referenced it like I would any other component:

1. create a 'aws-s3' folder wherever your components live

```
git clone https://github.com/Fausto95/aws-s3
mv aws-s3/src/* <PATH TO COMPONENTS FOLDER>/aws-s3
```

Then, in your code: 

```
import S3Client from './components/aws-s3'
<now use library like normal>
```

**Comment by guizero** [comment]
Hey @gatesyp ! I'll try that. So basically what is outside node_modules won't be minified, right?

**Comment by gatesyp** [comment]
@guizero If I remember correctly, everything will be minified during the build process. 

If the stuff inside node_modules was written with ES6, it will only get minified if they provide an ES5 configuration to transpile the code to ES5 first, and then the build process minifies it. 

All stuff outside node_modules will be automatically transpiled to ES5 and minified. 

The reason they don't do automatic conversion of ES6 libraries to ES5 is because it could lengthen the build process significantly in some cases, so for now they leave it up to the programmer. 

SO, the error with this library is that it does not properly convert the code to ES5 (probably a misconfiguration). If we include the library as our own application code, then the build process will automatically convert + minify it.

Hope that makes sense! I spent a decent amount of time looking into the problem, and this is how I understood it

**Comment by guizero** [comment]
That makes total sense @gatesyp . Thanks for that. I give you a feedback whenever I try your solution =)

**Comment by gatesyp** [comment]
@guizero sounds good!

**Comment by Fausto95** [comment]
Hi guys, @matveychuk @BrackCarmony @Evert-jvv @gatesyp @guizero I just published a new version with bug fixes.

If you install the last version(`1.5.5`) everything should be working correctly :)
`npm i aws-s3`

Feel to give any feedback and thank you guys for filling the issue!

**Comment by guizero** [comment]
It worked @Fausto95 ! Thanks
